// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://ipoeckdsktrkvnyjjcoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlwb2Vja2Rza3Rya3ZueWpqY29jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3Njg0NjksImV4cCI6MjA4MDM0NDQ2OX0.Q8z-B-JJyyYVoLywZXVpyPZnNlcviCeVIFu3S12aMos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
